# Generated by Django 6.0.3 on 2026-05-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="country",
            field=models.CharField(default="USA", max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country_code",
            field=models.CharField(default="+1", max_length=10),
        ),
    ]
