# Generated by Django 6.0.3 on 2026-05-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_userprofile_country_userprofile_country_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="country_code",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="mobile_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
