# Generated by Django 6.0.3 on 2026-05-15 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_remove_userprofile_country_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="country",
        ),
    ]
