# Generated by Django 6.0.3 on 2026-05-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_remove_userprofile_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="mobile_no",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
