# Generated by Django 6.0.3 on 2026-05-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0008_alter_userprofile_mobile_no"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="stock_quantity",
            new_name="stock",
        ),
        migrations.AddField(
            model_name="product",
            name="available_durations",
            field=models.CharField(
                default="3,6,12",
                help_text="Enter durations separated by commas (e.g. 3,6,12)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="deposit_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Deposit (₹)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="material",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_per_month",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Rent (₹/month)"
            ),
        ),
    ]
