# Generated by Django 6.0.3 on 2026-05-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0009_rename_stock_quantity_product_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/", verbose_name="Image 2"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/", verbose_name="Image 3"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                verbose_name="Primary Image",
            ),
        ),
    ]
