# Generated by Django 6.0.3 on 2026-05-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0010_product_image2_product_image3_alter_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image2",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image3",
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                verbose_name="Product Image",
            ),
        ),
    ]
