# Generated by Django 6.0.3 on 2026-05-15 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0011_remove_product_image2_remove_product_image3_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="deposit_amount",
        ),
    ]
