# Generated by Django 6.0.3 on 2026-05-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0014_rentalorder_payment_method_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_resolved", models.BooleanField(default=False)),
            ],
        ),
    ]
