# Generated by Django 6.0.3 on 2026-05-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0015_contactquery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Sofa", "Sofa"),
                    ("Bed", "Bed"),
                    ("Dining", "Dining Table"),
                    ("Table", "Tables & Desks"),
                    ("Living", "Living Room"),
                    ("Office", "Office & Study"),
                    ("Appliances", "Appliances"),
                    ("Others", "Others"),
                ],
                max_length=50,
            ),
        ),
    ]
