# Generated by Django 6.0.3 on 2026-05-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0016_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_cleared_count",
            field=models.IntegerField(default=0),
        ),
    ]
