# Generated by Django 6.0.3 on 2026-05-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0017_userprofile_last_cleared_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="country",
            field=models.CharField(default="India", max_length=100),
        ),
    ]
