# Generated by Django 6.0.3 on 2026-05-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0018_userprofile_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="dismissed_notifications",
            field=models.TextField(blank=True, default=""),
        ),
    ]
