# Generated by Django 6.0.3 on 2026-05-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0019_userprofile_dismissed_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalorder",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
